        const videoData = [
{ title: "BIOLOGY MENTORSHIP SESSION", videoId: "uPM53Lax6Xg" },
{ title: "CHEMISTRY MENTORSHIP SESSION", videoId: "JaWMEEB_iGc" },
{ title: "MATH MENTORSHIP SESSION", videoId: "olV8M7xp_sI" },
{ title: "EBI Mentorship Class", videoId: "xPMUGXdgs1Y" },
{ title: "PHYSICS MENTORSHIP SESSION", videoId: "TkVrn8T-ZlU" },
{ title: "সংখ্যাপদ্ধতি-০১", videoId: "iK-lo9RU6dA" },
{ title: "সংখ্যাপদ্ধতি পর্ব-০২", videoId: "l75rI34jB_k" },
{ title: "সংখ্যাপদ্ধতি (পর্ব-০৩)", videoId: "voSerxe4EAE" },
{ title: "ডিজিটাল ডিভাইস (পর্ব-০১)", videoId: "bARRLtrId7M" },
{ title: "ডিজিটাল ডিভাইস (পর্ব-০২)", videoId: "UOaOIvt_czA" },
{ title: "ডিজিটাল ডিভাইস (পর্ব-০৩)", videoId: "iQ5edgbw-CU" },
{ title: "ডিজিটাল ডিভাইস (পর্ব-০৪)", videoId: "lgP2WTpAWIU" },
{ title: "১ম অধ্যায়", videoId: "c2tWGo6n4E8" },
{ title: "ডেটাবেজ ম্যানেজমেন্ট সিস্টেম (পর্ব-০১)", videoId: "570152/d5be4e49-d55e-4cf4-9748-187342ac7772" },
{ title: "Topic: Modifier", videoId: "AWV1ro6RGs0" },
{ title: "Topic : Completing sentence & Paragraph Writing", videoId: "Aqx-UhthZUc" },
{ title: "Completing Sentence", videoId: "OHuxXa1jA0U" },
{ title: "Topic: Correct Form of Verbs-Part 01", videoId: "KStQbCt68Cc" },
{ title: "Topic: Correct Form of Verbs-Part 02", videoId: "9w9vlPPuwDU" },
{ title: "The basic discussion of Narration", videoId: "hQyBo-MVZqs" },
{ title: "Pronoun Reference", videoId: "4_bHsco2tC4" },
{ title: "Sentence Connectors", videoId: "V4cePIPuMkw" },
{ title: "Narration Lecture 2", videoId: "78wDRipAhcc" },
{ title: "Preposition", videoId: "ga8m4-xztbg" },
{ title: "জটিল সংখ্যা", videoId: "dtj4kGIKa2M" },
{ title: "বহুপদী ও বহুপদী সমীকরণ (Part-1)", videoId: "csDRee8Tp_s" },
{ title: "বহুপদী ও বহুপদী সমীকরণ (Part-2)", videoId: "IraIKpoDT9M" },
{ title: "বিস্তার পরিমাপ ও সম্ভবনা(পর্ব-০১)", videoId: "vvO2V2PvGRc" },
{ title: "বিস্তার পরিমাপ ও সম্ভবনা(পর্ব-০২)", videoId: "TRCXgal2ySk" },
{ title: "বাস্তব সংখ্যা ও অসমতা", videoId: "joSj_l2jbyE" },
{ title: "কণিকস (পর্ব-০১)", videoId: "9WTcqtKY0uA" },
{ title: "কণিকস (পর্ব-০২)", videoId: "-Kt5yJSEbA8" },
{ title: "যোগাশ্রয়ী প্রোগ্রামিং", videoId: "j41Ty1QTc88" },
{ title: "বিপরীত ত্রিকোণমিতিক ফাংশন ও  ত্রিকোণমিতিক সমীকরণ(পর্ব-০১)", videoId: "ae4p5nblUZI" },
{ title: "বিপরীত ত্রিকোণমিতিক ফাংশন ও ত্রিকোণমিতিক সমীকরণ(পর্ব-০২)", videoId: "fYQbl42BQcY" },
{ title: "স্থিতিবিদ্যা(পর্ব-০১)", videoId: "TkXHtWHqApo" },
{ title: "স্থিতিবিদ্যা(পর্ব-০২)", videoId: "07Hd_-4E1Lg" },
{ title: "সমতলে বস্তুকণার গতি-(পর্ব-০১)Part-01", videoId: "9uxKbMfT7CY" },
{ title: "সমতলে বস্তুকণার গতি-(পর্ব-০১)Part-02", videoId: "eL6lCW8nzVQ" },
{ title: "সমতলে বস্তুকণার গতি-(পর্ব-০২)", videoId: "0Tyr0oUjg5g" },
{ title: "দ্বিপদী বিস্তৃতি - পর্ব ০১", videoId: "YEKaZqT5538" },
{ title: "দ্বিপদী বিস্তৃতি - পর্ব ০২", videoId: "bwWkzVXO4YA" },
{ title: "দ্বিপদী বিস্তৃতি পর্ব ২ (Last Part)", videoId: "k4BoVRrnlkA" },
{ title: "পরিমাণগত রসায়ন (পর্ব ১)", videoId: "Qxmp4EeI6EU" },
{ title: "পরিমাণগত রসায়ন (পর্ব ২)", videoId: "NwVR9w0yzQQ" },
{ title: "পরিমাণগত রসায়ন (পর্ব ৩)", videoId: "8MLckn_SDE4" },
{ title: "পরিমাণগত রসায়ন (পর্ব ৪)", videoId: "0iXWs77tBkI" },
{ title: "পরিবেশ রসায়ন (পর্ব ১)", videoId: "JkUOau5paVw" },
{ title: "পরিবেশ রসায়ন (পর্ব ২)", videoId: "F7im_JADR-0" },
{ title: "পরিবেশ রসায়ন (পর্ব-০৩)", videoId: "OFvWBgJhZKA" },
{ title: "পরিবেশ রসায়ন (পর্ব-৪)", videoId: "Fb6nC_r5Gw8" },
{ title: "তড়িৎ রসায়ন (পর্ব-০১)", videoId: "-nJSVePnX88" },
{ title: "তড়িৎ রসায়ন (পর্ব-০২)", videoId: "94ZXf7N3DH4" },
{ title: "অর্থনৈতিক রসায়ন", videoId: "xe-1-dPqyuc" },
{ title: "জৈব যৌগ (পর্ব-০১)", videoId: "Ph4a-bIdTMY" },
{ title: "জৈব যৌগ (পর্ব-০২)", videoId: "spdbyCTg4_4" },
{ title: "জৈব যৌগ (পর্ব-০৩)", videoId: "uuCU9KfRqvo" },
{ title: "জৈব যৌগ (পর্ব-০৪)", videoId: "nHuLe7OGKW0" },
{ title: "জৈব যৌগ (পর্ব-০৫)", videoId: "xiYu6xgFvf0" },
{ title: "জৈব যৌগ (পর্ব-০৬)", videoId: "570152/7592a804-7b75-402a-ae40-69413012562a" },
{ title: "জৈব যৌগ (পর্ব-০৭)", videoId: "570152/19aeaa22-b017-405d-b19a-2a277c8a2cdd" },
{ title: "জৈব যৌগ-(পর্ব-০৮)", videoId: "570152/3f318998-fb62-40d1-b6e5-2bd34389874a" },
{ title: "জৈব যৌগ-(পর্ব-০৯)", videoId: "570152/e0be512e-8887-476b-ab63-bbfc671b91ec" },
{ title: "জৈব যৌগ-(পর্ব-১০)", videoId: "570152/028e0739-256a-4a3a-9bec-b70f246733d9" },
{ title: "তাপগতিবিদ্যা (পর্ব ১)", videoId: "nxVrNvcF1gg" },
{ title: "তাপগতিবিদ্যা (পর্ব ২)", videoId: "iKgoLAZdtZQ" },
{ title: "চল তড়িৎ (পর্ব-০১)", videoId: "7xb15PjCKuw" },
{ title: "চল তড়িৎ (পর্ব-০২)", videoId: "NkjXvyaAh6s" },
{ title: "চল তড়িৎ(পর্ব ৩ - part -01)", videoId: "Y6NMHXLkqsE" },
{ title: "চল তড়িৎ(পর্ব ৩ - part -02)", videoId: "gJ83lRK2wrg" },
{ title: "তাড়িতচুম্বক আবেশ ও দিক পরিবর্তি প্রবাহ", videoId: "Fzv2yjGdXT0" },
{ title: "তাড়িতচুম্বক আবেশ ও পরিবর্তি প্রবাহ বাকী অংশ( সিকিউ সহ)", videoId: "5b3moH1Cil8" },
{ title: "স্থির তড়িৎ (পর্ব০১-Part-01)", videoId: "N4R7sFlMHlc" },
{ title: "স্থির তড়িৎ (পর্ব০১-Part-02)", videoId: "B0fAqaBE6XM" },
{ title: "স্থির তড়িৎ (পর্ব০১-Part-03)", videoId: "tkuMsIO0c0E" },
{ title: "স্থির তড়িৎ (পর্ব০২)", videoId: "9ip85af8gJk" },
{ title: "তড়িৎ প্রবাহে চৌম্বক ক্রিয়া (পর্ব-০১)", videoId: "FGNKmFfQeMQ" },
{ title: "তড়িৎ প্রবাহে চৌম্বক ক্রিয়া (পর্ব-০২)", videoId: "PDpsQWNGuVg" },
{ title: "আধুনিক পদার্থবিজ্ঞানের সূচনা", videoId: "s0wKAWzNDg4" },
{ title: "ভৌত আলোকবিজ্ঞান", videoId: "EMUCgx1E9_g" },
{ title: "জ্যামিতিক আলোকবিজ্ঞান -(পর্ব ০১)", videoId: "IbYiNKU7pn0" },
{ title: "জ্যামিতিক আলোকবিজ্ঞান -(পর্ব ০২)", videoId: "PYqspDPANHM" },
{ title: "সেমিকন্ডাক্টার,ইলেকটনিক্স", videoId: "CtD_P4dt_F4" },
{ title: "পারমাণবিক পদার্থবিজ্ঞান (পর্ব-০১)", videoId: "2N9tt0J43qw" },
{ title: "রক্ত ও সংবহন (পর্ব-০১)", videoId: "0s-K-wv1Ym8" },
{ title: "রক্ত ও সংবহন (পর্ব-০২)", videoId: "TnEeRzrx8jY" },
{ title: "জিনতত্ত্ব ও বিবর্তন (Part 1 )", videoId: "OVEia2xzR1M" },
{ title: "জিনতত্ত্ব ও বিবর্তন (Part 2 )", videoId: "1qHmpY5yfh8" },
{ title: "শ্বসন ও শ্বাসক্রিয়া", videoId: "suTJQaWwGBE" },
{ title: "বর্জ্য ও নিষ্কাশন", videoId: "Bfjbhc1STMM" },
{ title: "রুই মাছ (Patr-01)", videoId: "rIAEB5BxJWo" },
{ title: "রুই মাছ (Patr-02)", videoId: "ChO1_fmOJZE" },
{ title: "হাইড্রা", videoId: "RJ1nKupOc_c" },
{ title: "ঘাস ফড়িং", videoId: "gmbqyIp9q9A" },
{ title: "প্রাণীর বিভিন্নতা ও শ্রেণিবিন্যাস", videoId: "-z2RoldFtwg" },
{ title: "চলন ও অঙ্গচালনা Part-01", videoId: "6m4CqqkqahU" },
{ title: "চলন ও অঙ্গচালনা Part-02", videoId: "QrVALrrOtsM" },
{ title: "পরিপাক ও শোষণ", videoId: "fMldMnswD5M" },
{ title: "সমন্বয় ও নিয়ন্ত্রণ(পর্ব-০২)", videoId: "wjIu7pqtBPc" },
{ title: "সমন্বয় ও নিয়ন্ত্রণ(পর্ব-০১)", videoId: "570152/87ac38c3-94ab-4aff-b6b1-49519ce39546" },
{ title: "মানব দেহের প্রতিরক্ষা", videoId: "wYXZAqplyXY" },
{ title: "মানবজীবনের ধারাবাহিকতা", videoId: "570152/1e237d9a-bcf5-4298-b3c1-a2fb7388129b" },
{ title: "প্রানীর আচরন", videoId: "570152/7c48951f-e566-4401-a22e-f92cf6a53554" },
{ title: "ব্যাকরণিক শব্দশ্রেণি-0১ + তাহারেই পড়ে মনে", videoId: "PVcJjU8tdtY" },
{ title: "যৌবনের গান+ব্যাকরণিক শব্দশ্রেণি-২", videoId: "2jTgvYrtNgM" },
{ title: "অপপ্রয়োগ", videoId: "7GK3_s7RMMY" },
{ title: "সোনার তরী - বাক্যতত্ত্ব -আঠারো বছর বয়স", videoId: "KGlHm2zZQeA" },
{ title: "বাক্যতত্ত্ব ও বিদ্রোহী", videoId: "G28XEYXk54I" },
{ title: "বাঙালা নব্য - প্রতিদান", videoId: "Cgzmqf3xu9s" },
{ title: "সমাস - পর্ব ০১", videoId: "L_8SRL5_XNs" },
{ title: "সমাস - পর্ব ০২", videoId: "01jMj-YH94I" },
{ title: "সমাস - পর্ব ০৩", videoId: "570152/22eaaa77-f76c-492f-bdd7-818874351541" },
{ title: "লালসালু", videoId: "qIiUxsd5Rsg" },
{ title: "আমি কিংবদন্তির কথা বলছি ও মাসি পিসি", videoId: "vAjQ_iG8D0c" },
{ title: "উচ্চারণ-১", videoId: "570152/22eaaa77-f76c-492f-bdd7-818874351541" },
{ title: "উচ্চারণ-২", videoId: "570152/7722fe5d-ca11-45e2-85c1-ad1b4a8c50ae" },
{ title: "বানান", videoId: "570152/d6f228ba-7c3b-425c-acd4-22bb434b205f" },
{ title: "বিভীষণের প্রতি মেঘনাদ + উপসর্গ", videoId: "570152/4593697f-fba6-4790-bfc6-fdac5e2e497e" },
{ title: "নেকলেস + রেইকোট", videoId: "570152/34b7519a-a511-4cb7-ad16-1010ee6c073c" },
{ title: "বিলাসী, প্রতিদান", videoId: "570152/f86c3491-491b-451d-888c-7769937deaf1" },
        ];